import { mount } from 'svelte';
import { dom, library } from "@fortawesome/fontawesome-svg-core";
import {
  faAddressCard,
  faArrowLeft,
  faBold,
  faBook,
  faCalendarDays,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCloudArrowUp,
  faCode,
  faFloppyDisk,
  faFileLines,
  faFolderTree,
  faGripLines,
  faImage,
  faItalic,
  faLayerGroup,
  faLink,
  faListOl,
  faListUl,
  faNoteSticky,
  faPenToSquare,
  faPlus,
  faQuoteLeft,
  faStrikethrough,
  faTags,
  faTrash,
  faUser,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import App from "./App.svelte";

library.add(
  faAddressCard,
  faArrowLeft,
  faBold,
  faBook,
  faCalendarDays,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCloudArrowUp,
  faCode,
  faFloppyDisk,
  faFileLines,
  faFolderTree,
  faGripLines,
  faImage,
  faItalic,
  faLayerGroup,
  faLink,
  faListOl,
  faListUl,
  faNoteSticky,
  faPenToSquare,
  faPlus,
  faQuoteLeft,
  faStrikethrough,
  faTags,
  faTrash,
  faUser,
  faXmark,
);
dom.watch();

const app = mount(App, {
  target: document.getElementById("app")!,
})

export default app
